import {
  DeleteObjectsCommand,
  ListObjectsV2Command,
  PutObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3";

const client = new S3Client({});

export async function putDocument(bucket, key, body) {
  await client.send(
    new PutObjectCommand({
      Bucket: bucket,
      Key: key,
      Body: JSON.stringify(body),
      ContentType: "application/json",
    }),
  );
}

/**
 * Remove documents belonging to earlier runs while leaving documents already
 * generated by the current run alone. Calling this at the start of every tick
 * keeps the scheduled Lambda stateless and makes an interrupted cleanup safe
 * to retry on the next invocation.
 */
export async function deletePreviousDocuments(bucket, currentRunId) {
  const currentPrefix = `documents/${currentRunId}/`;
  const previousKeys = [];
  let continuationToken;

  do {
    const page = await client.send(
      new ListObjectsV2Command({
        Bucket: bucket,
        Prefix: "documents/",
        ContinuationToken: continuationToken,
      }),
    );

    for (const object of page.Contents ?? []) {
      if (object.Key && !object.Key.startsWith(currentPrefix)) {
        previousKeys.push(object.Key);
      }
    }
    continuationToken = page.NextContinuationToken;
  } while (continuationToken);

  for (let offset = 0; offset < previousKeys.length; offset += 1000) {
    const keys = previousKeys.slice(offset, offset + 1000);
    const result = await client.send(
      new DeleteObjectsCommand({
        Bucket: bucket,
        Delete: {
          Objects: keys.map((Key) => ({ Key })),
          Quiet: true,
        },
      }),
    );

    if (result.Errors?.length) {
      const details = result.Errors.map(({ Key, Code }) => `${Key}: ${Code}`).join(", ");
      throw new Error(`failed to delete previous documents: ${details}`);
    }
  }

  return previousKeys.length;
}
